### ISSUE TITLE
Works only white standing + potential workaround

### ISSUE THREAD

**Issue by Msulecki** [RobertWojtowicz/miscale2garmin#14]
Hi, I have a problem to make scripts work properly. Reading complete data from scale works only while I'm standing on it. If not, `hasImpedance` variable always results in 0, so i get incomplete data as output and therefore, upload to garmin connect fails.

 I've noticed that if i turn of "weigh small object" option in dedicated app, i can get proper results almost every time event when i'm not standing on scale anymore. I wonder if anyone experienced this bahavior. It's weird because app gets results everytime, despite of selected options.
 
 I'm using scripts with rPi4 if that matters.

**Comment by RobertWojtowicz** [comment]
Hi @Msulecki

It always works fine for me, I think it's a matter of measurement time:
- try to take the measurement, but wait until the progress bar stops flashing;
- get off the scale.
Let me know if it helped.

It may be also too short range of BT module in rPi4 ?

BR,
Robert

**Comment by Msulecki** [comment]
> 
> It may be also too short range of BT module in rPi4 ?
> 

I think it could be the case, when I move scale near Raspberry, i think I get results all the time (but only with disabled weight small object option still). I'm gonna try ESP32 option too, as I have few of them with me.

**Comment by RobertWojtowicz** [comment]
Add to Readme disable weigh small object

**Comment by RobertWojtowicz** [comment]
@Msulecki check Readme: https://github.com/RobertWojtowicz/miscale2garmin/blob/master/README.md
