### ISSUE TITLE
There is no new data to upload to Garmin Connect

### ISSUE THREAD

**Issue by FredFreegroup** [RobertWojtowicz/miscale2garmin#17]
Hi
Something goes wrong. I didn`t get where is a problem.

ESP32 working well
10:00:30.999 -> * Starting BLE scan:
10:00:31.739 ->   BLE device found with address: 64:df:e8:..... non-target device
10:00:31.784 ->   BLE device found with address: 6c:88:26:....., non-target device
10:00:31.923 ->   BLE device found with address: ec:fa:5c:...., non-target device
10:00:32.616 ->   BLE device found with address: c7:dd:15:..... <= target device
10:00:32.616 -> * Reading BLE data complete, finished BLE scan
10:00:33.351 -> * Connecting to WiFi: connected
10:00:35.886 ->   IP address: 192.168.31.231
10:00:35.886 -> * Connecting to MQTT: connected
10:00:36.766 -> * Publishing MQTT data: 82.00;331;1660204397;to_import;2022-8-11 9:53:17;4.09;90
10:00:36.766 -> * Waiting for next scan, going to sleep

But when I start import_data.sh it doesn't send anything to Garmin.

* Creating backup.csv file, checking for new data
* Importing data from MQTT broker
* (here I added to the log readed var)
read_scale: 82.00;331;1660204397;to_import;2022-8-11 9:53:17;4.09;90
* -2850 s time difference, synchronize date and time scale
* There is no new data to upload to Garmin Connect

When I start it again - changind time difference all time
backup.csv is empty.

**Comment by FredFreegroup** [comment]
I think I get
I think problem is in time zone
unixtime_os = 1660208847
Thursday, 11 August 2022 р., 09:07:27
but my os time is 
Thursday, 11 August 2022 р., 12:07:27

**Comment by RobertWojtowicz** [comment]
As I wrote in the instructions:
```
The following information must be entered before compiling code (esp32.ino) in Arduino IDE:
- other settings ("led_pin", "**Timestamps**", "Battery18650Stats");
```

**Comment by RobertWojtowicz** [comment]
I additionally added in the Readmie file:
- If time is still not synchronizing correctly, check NTP synchronization on your server or check time offset if you are using ESP32 (Timestamp parameter in esp32.ino);
