### ISSUE TITLE
Scale timestamp is always UTC

### ISSUE THREAD

**Issue by klaboor** [RobertWojtowicz/miscale2garmin#18]
Hi Robert,
I would like to report time zone mismatch between scale and OS (raspberry OS in my case).
I carefully followed your instructions how to set correct date and time for scale, but it didn't work for me. No matter what I do, it still returns UTC time, so time doesn't match for me. My local time is UTC+1 summertime so it's 2 hours difference. I was forced to modify import_data.sh and change threshold value from 1200s to 8400s (1200 + 7200(2 hours difference between scale and local time)).
I'm not sure if different account for Zepp Life (I use Mi account currently) will fix/change time. I can try this.
Anyway, I know how hard is to work in environment with multiple time zones. In such cases where scale doesn't respect local time it would be handy to have feature to apply some kind of offset automatically (like I did manually) by prompting user if he wants to apply time difference offset.

**Comment by RobertWojtowicz** [comment]
Hi @klaboor ,

Which version are you using ESP32 or BLE ?

BR,
Robert

**Comment by manfredviii** [comment]
even for myself. l
It works, but on garmin I see the wrong time for weighing.
I use BLE with raspberry (italy fuse)

Il sab 10 set 2022, 12:57 Robert Wójtowicz ***@***.***> ha
scritto:

**Comment by RobertWojtowicz** [comment]
Strange, I don't have this case (Poland UTC +2), maybe it's a matter of setting the time zone in Garmin Connect ?
![image](https://user-images.githubusercontent.com/19271127/189481457-3ec99ffa-a70f-4e7a-bb58-f02010c042c0.png)
Unix time is always the same for each time zone. Alternatively, I would look for the problem in the operating system or in the time settings on the scale.

**Comment by manfredviii** [comment]
I think the problem is in the scale settings, but I don't know how I can
check the time or change the time on the scale

Il sab 10 set 2022, 13:40 Robert Wójtowicz ***@***.***> ha
scritto:

**Comment by klaboor** [comment]
I use BLE version. I tried Zepp Life account instead of Mi account and also take out batteries with no difference.
Garmin Connect time zone setting has nothing to do with it, but I checked it and it's OK. 
I check backup.csv and see upload time (os time) vs scale time like this for example.
2022-09-09 09:35:12;2022-9-9 7:30:21

This is how current scale scan and raspberry OS time settings looks like (ignore 4 minutes difference. It's 4 minutes between commands):
![scaleScan](https://user-images.githubusercontent.com/35469080/189484007-b3e2a509-14e2-4f4b-9cdb-6b679dc67d16.PNG)
![rpiTimeSettings](https://user-images.githubusercontent.com/35469080/189484065-73ab3ed8-0f54-4f7a-bc42-742e0114fb38.PNG)

About scale settings related to date and time, there is nothing I can change. The only thing is to pickup correct country/region during account creation process, but that's it. Nothing else.
I don't think we can modify scale time settings.

**Comment by RobertWojtowicz** [comment]
Hi, @klaboor,

Just as I thought you have a problem with setting the correct time on the scale.
Check your smartphone settings and the Zepp Life app.
For example, today's my weighing in backup.csv file:
56.50;579;1662812493;uploaded;2.56;19.10;12.74;59.86;23;46.74;6.00;4.75;2022-09-10 14:19:11;2022-9-10 14:21:33

**Comment by klaboor** [comment]
I tried everything and unfortunately gave up.

Phone (iPhone XR) date, zone and time settings, are correct. Zepp account region is correct. App was reinstalled with scale data cleared, removed pairing and paired back with fresh weighing. No change at all. Zepp Life app doesn't provide date time settings. Scale manual have also 0 references to date and time settings. Standard users doesn't even know the scale has time property active, because standard users will not be doing bluetooth transmission scanning :)

I tried also Android phone (Xiaomi Mi A3) and was hoping that maybe android app will provide more settings, but no. It's same but I repeat all steps with same result.
I checked scale firmware (is up to date) and allowed all app permissions like localization, etc. Still nothing.

I can modify script by myself, no problem, but it can be frustrating for someone else without scripting background who will follow instructions and end up with time missmatch like I did.

**Comment by RobertWojtowicz** [comment]
> I can modify script by myself, no problem, but it can be frustrating for someone else without scripting background who will follow instructions and end up with time missmatch like I did.

Suggest changes, it seems to me that you need to change in the scanner_ble.py file, because the time offset in esp32 is implemented at the esp32 program level.

**Comment by RobertWojtowicz** [comment]
> I can modify script by myself, no problem, but it can be frustrating for someone else without scripting background who will follow instructions and end up with time missmatch like I did.

Suggest changes, it seems to me that you need to change in scanner_ble.py file, because the time offset in esp32 is implemented at the esp32 program level.

**Comment by RobertWojtowicz** [comment]
> I can modify script by myself, no problem, but it can be frustrating for someone else without scripting background who will follow instructions and end up with time missmatch like I did.

I rebuilt the synchronization to rely only on Unix timestamps everywhere (ESP32 + BLE) + offset in the import_data.sh file, check the new version 4.4
