### ISSUE TITLE
any way to skip a certain user?

### ISSUE THREAD

**Issue by 1v0dev** [RobertWojtowicz/miscale2garmin#19]
Hi, I use miscale together with my wife. She does not have garmin account so I don't need to upload her data therefore I have not added her to the `users` array. But her data appears in the backup.csv files and once there it stops the upload of any further readings saying "There is no user with the given weight...". Is there anyway to modify the script so it just skips her data based on max weight?

**Comment by RobertWojtowicz** [comment]
I think I have an idea how to solve it, I only need time :)

I will add a few changes to: import.sh and export.py, so that when checking temp.log file in this case line with this data will be deleted.

BR,
Robert

**Comment by 1v0dev** [comment]
That would be awesome. Thank you very much!

**Comment by RobertWojtowicz** [comment]
> That would be awesome. Thank you very much!
Download version 4.5 problem solved.
