### ISSUE TITLE
Can this be run on linux server directly?

### ISSUE THREAD

**Issue by apkraven** [RobertWojtowicz/miscale2garmin#2]
Hi, Robert, 
looks like great work, but have a question. 
I have a linux ubuntu server, it has Bluetooth built-in. Can this be somehow run on a linux machine without the need for the hardware project? I even have an mqtt server installed there, so would just appreciate some way to use the built-in BT to query the scale without building that chargeable external hardware box. 
PS> I'm looking for a way to export the body parameters to garmin connect.

**Comment by RobertWojtowicz** [comment]
Hi, @apkraven 

Yes of course, take a look at these projects:
https://github.com/wiecosystem/Bluetooth
https://github.com/lolouk44/xiaomi_mi_scale

Best Regards,
Robert

**Comment by apkraven** [comment]
Robert, that's brilliant. That looks superb, the second link is even a hassio-addon, so it's built In the home assistant which I also happen to have. Not that I wanted to plan automation depending on how fat I become, but that still looks promising and seems I should be able to figure out how to take the first part from their mqtt streaming and your second part to read it and export to garmin connect. 
Thanks a lot :)

**Comment by RobertWojtowicz** [comment]
I added a new version supporting direct synchronization
