### ISSUE TITLE
stuck on "Importing data from BLE device"

### ISSUE THREAD

**Issue by vobo70** [RobertWojtowicz/miscale2garmin#20]
Hi Robert,
I just managed to install VM with Debian 11 / Baseus BA04 BT 5.1 usb dongle
and scan works perfectly:
`root@miscale:/opt/miscale2garmin-4# python3 ./scanner_ble.py
Mi Body Composition Scale 2 Garmin Connect v4.4 (scanner_ble.py)

* Starting BLE scan:
  BLE device found with address: 0c:95:41:15:9a:df <= target device
* Reading BLE data complete, finished BLE scan`

but ./import_data.sh
is stuck on:
`root@miscale:/opt/miscale2garmin-4# ./import_data.sh
Mi Body Composition Scale 2 Garmin Connect v4.6 (import_data.sh)

* Backup.csv file exists, checking for new data
* Importing data from BLE device`

Please help me how to solve this
Regards,
Maciek

**Comment by vobo70** [comment]
Hi again
I moved scale to same room as vm host
Time is synced but now I get:
`root@miscale:/opt/miscale2garmin-4# ./import_data.sh
Mi Body Composition Scale 2 Garmin Connect v4.6 (import_data.sh)

* Backup.csv file exists, checking for new data
* Importing data from BLE device
* No BLE data from scale or incomplete
* There is no new data to upload to Garmin Connect`

**Comment by vobo70** [comment]
just in case - maybe you know - are there correct settings for NTP for debian 11?
`root@miscale:/opt/miscale2garmin-4# timedatectl
               Local time: Sat 2022-10-01 09:02:41 CEST
           Universal time: Sat 2022-10-01 07:02:41 UTC
                 RTC time: Sat 2022-10-01 07:02:42
                Time zone: Europe/Warsaw (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no`
I think mainly about: RTC in local TZ: no

**Comment by RobertWojtowicz** [comment]
"No BLE data from scale or incomplete" > Run scanner_ble.py to see if you get weighted data

**Comment by vobo70** [comment]
root@miscale:/opt/miscale2garmin-4# python3 ./scanner_ble.py
Mi Body Composition Scale 2 Garmin Connect v4.4 (scanner_ble.py)

* Starting BLE scan:
  BLE device found with address: 0c:95:41:15:9a:df <= target device
* Reading BLE data incomplete, finished BLE scan

**Comment by vobo70** [comment]
OK - I will check README - so wait for now.

**Comment by RobertWojtowicz** [comment]
do you have a measurement ? e.g. "59.35;511;1654529140"

**Comment by vobo70** [comment]
OK - I will work on it
you're right (hopefully)
