### ISSUE TITLE
* Reading BLE data incomplete, finished BLE scan

### ISSUE THREAD

**Issue by mic-hall** [RobertWojtowicz/miscale2garmin#22]
Hi, I have set up all things according to the guide, but the "scanner_ble.py" gets always "Reading BLE data incomplete". I downloaded the new version 4.8 but this still gets the same message.

**Comment by RobertWojtowicz** [comment]
> Hi, I have set up all things according to the guide, but the "scanner_ble.py" gets always "Reading BLE data incomplete". I downloaded the new version 4.8 but this still gets the same message. 

What model of scale ?

**Comment by mic-hall** [comment]
Same as on your guide - XMTZC05HM, firmware 1.0.0.12

**Comment by mic-hall** [comment]
I see in the "closed" issues there is a similar case "Help for Error "Reading BLE data incomplete, finished BLE scan" #7. Seems my scale does not report the impedance measurement, but in the app all measures work.

**Comment by mic-hall** [comment]
I managed to get the correct measurement. You need to stand on the scale just a bit longer :-). Issue solved !
