### ISSUE TITLE
Bluetooth adapter interface problem

### ISSUE THREAD

**Issue by deracloust** [RobertWojtowicz/miscale2garmin#24]
There were some problems with my bluetooth adapter interface during installation. In your code, you are using the `hci0` interface of the bluetooth adapter by default.
This can be problematic for people who have multiple bluetooth adapters.

I just had to add a parameter to the `Scanner` function in the `scanner_ble.py` file - line 50 (in my case the bluetooth adapter is on the hci1 interface):

`scanner = btle.Scanner(1)`.

I suggest adding this information to the README. It may help many people :)

Thanks!

**Comment by RobertWojtowicz** [comment]
Hi @deracloust,

thanks for the info.
I created a new version, changes in readme and scanner_ble.py:
https://github.com/RobertWojtowicz/miscale2garmin/releases/tag/5

Just out of curiosity why do you need more bluetooth devices ?

BR,
Robert

**Comment by deracloust** [comment]
I'm running my home server on old laptop with debian installed. The laptop has built in bluetooth module, which handels Bluetooth 2.0. Most of devices and softwares (including bluepy) requires atleast Bluetooth 4.0, so simplest way for me to fix it was to use external USB dongle.

Best regards and happy new year!
Michał

**Comment by RobertWojtowicz** [comment]
> I'm running my home server on old laptop with debian installed. The laptop has built in bluetooth module, which handels Bluetooth 2.0. Most of devices and softwares (including bluepy) requires atleast Bluetooth 4.0, so simplest way for me to fix it was to use external USB dongle.>

I already understand everything.
Then I have to think after the new year about the correlation of the hci parameter with the verification of the hci device, specifically this line:
``if len(os.popen("hcitool dev | awk 'NR>1 {print $2}'").read()) == 0:``

**Comment by RobertWojtowicz** [comment]
Hi @deracloust,

I think I have a solution:
``if len(os.popen(f"hcitool dev | awk 'NR>{hci + 1} {{print $2}}'").read()) == 0:``

Can you tell me what hcitool dev returns ?

BR,
Robert

**Comment by deracloust** [comment]
`michal@homeserver:~$ hcitool dev
Devices:
	hci1	00:1F:E1:C1:55:21
	hci0	04:7F:0E:17:A5:30
`

**Comment by deracloust** [comment]
Result of: `hcitool dev | awk 'NR> 1 {print $2}'`:
`00:1F:E1:C1:55:21 04:7F:0E:17:A5:30`

Result of : `hcitool dev | awk 'NR> 2 {print $2}'`:
`04:7F:0E:17:A5:30`

In case of list of bluetooth devices, i was thinking its going from smallest to largest due my rfkill blocks which I made during debugging the scale, but after reboot it's still the same.

**Comment by RobertWojtowicz** [comment]
ok, in a week I will take another bluetooth and it will improve the security for hci detection

**Comment by RobertWojtowicz** [comment]
@deracloust

download latest version 5.2 I corrected, hcitool dev lists in this order (as in your case):
hci2
hci1
hci0
