### ISSUE TITLE
Import successful but nothing on Garmin Connect

### ISSUE THREAD

**Issue by scastellanosnqn** [RobertWojtowicz/miscale2garmin#27]
Hi, first of all, thanks for this project, seems like a life saver for Garmin users.
I've recenetly setup miscale2garmin an I'm strugglin to get data on Garmin connect, everything seems fine. but nothing appears on Garmin Connect:
```* backup.csv file exists, check if temp.log exists
* temp.log file exists, checking for new data
* Importing data from a BLE scanner
* Saving import 1674745428 to backup.csv file
* Calculating data from import 1674745428, upload to Garmin Connect
* Data upload to Garmin Connect is complete
* Saving calculated data from import 1674745428 to backup.csv file```
The only strange thing I've notice is some really big offset, that I bypass by setting `offset: -11000`
```

Backup file seems fine:
```Data Status;Unix Time;Date;Time;Weight [kg];Change [kg];BMI;Body Fat [%];Skeletal Muscle Mass [kg];Bone Mass [kg];Body Water [%];Physique Rating;Visceral Fat;Metabolic Age [years];Impedance;Email User;Upload Date;Upload Time;Difference Time [s]
uploaded;1674744927;26.01.2023;11:55;83.2;0.0;26.9;26.6;57.9;3.1;50.3;2;17;38;432;santiago@***.com;26.01.2023;11:59;220
uploaded;1674745428;26.01.2023;12:03;83.2;0.0;26.9;26.6;57.9;3.1;50.3;2;17;38;434;santiago@***.com;26.01.2023;12:07;204
uploaded;1674745503;26.01.2023;12:05;83.0;-0.2;26.8;26.5;57.9;3.1;50.4;2;17;38;434;santiago@***.com;26.01.2023;12:08;205
```

What could be failing ?

**Comment by RobertWojtowicz** [comment]
H @scastellanosnqn ,

Very large offset, have you tried to synchronize time in the scale ?

What is content of temp.log file ? (you sent only backup, and logs from the script import_data.sh)

Maybe there is some other error that I did not handle in temp.log.

BR,
Robert

**Comment by RobertWojtowicz** [comment]
Hi, @scastellanosnqn,

In my case synchronization works correctly. Did you make it to check again ?

BR,
Robert

**Comment by RobertWojtowicz** [comment]
@scastellanosnqn

Maybe you're using 2FA or MFA auth:
https://github.com/lswiderski/mi-scale-exporter/issues/14

BR,
Robert

**Comment by mic-hall** [comment]
It may also be that you have downloaded the wrong execution version of the bodycomposition file (see the instructions). Something similar happened to me. You will see 'uploaded' data in backup.csv but also an execution error in temp.log

**Comment by RobertWojtowicz** [comment]
@mic-hall

Can you send me what you have in temp.log as it is the wrong version ?
In the import_data.sh file I included catching this type of error, in this case the word "Exec"
``
elif grep -q "Error\|panic\|denied\|There\|Exec" $path/temp.log ; then
``

**Comment by mic-hall** [comment]
`sh: 1: /home/pi/miscale2garmin-5/bodycomposition: not found

Mi Body Composition Scale 2 Garmin Connect v5.3 (export_garmin.py)

* Import data: 1678431421;80.0;484
* Calculated data: 10.03.2023;07:57;80.0;25.2;25.0;56.9;3.1;51.4;2;16;38;484;michal.kubicki@me.com;10.03.2023;07:59`

**Comment by RobertWojtowicz** [comment]
@mic-hall
I added an additional error handling in the import_data.sh file.
https://github.com/RobertWojtowicz/miscale2garmin/releases/tag/5

He usually occurs as it does not find bodycomposition file.
