### ISSUE TITLE
miscale2garmin via Home Assistant

### ISSUE THREAD

**Issue by alepevi** [RobertWojtowicz/miscale2garmin#28]
I am collecting the data from the Mi Scale 2 via Mqtt with Home Assistant (https://github.com/dckiller51/bodymiscale). Could that data be used to send it to Garmin Connect? If I understood how python files work, I think it would be easy to do, but it's beyond me. External projects can be integrated into Home Assistant via HACS. In fact, I see that your project is based on one of the projects that collect the data from the scale and send it to the Home Assistant. Could your project be integrated into Home Assistant? Sorry if I said nonsense. Thanks in advance.

**Comment by RobertWojtowicz** [comment]
Unfortunately no, it is prepared only for function of synchronization between scale and Garmin Connect.
