### ISSUE TITLE
AWK command and the resulting data/backup.csv

### ISSUE THREAD

**Issue by apkraven** [RobertWojtowicz/miscale2garmin#3]
Hi, I'm doing the modification for direct parsing parameters from mi scale and posting them to Garmin connect.
Could you please provide: 
1. the result of doing the read_MQTT=`mosquitto_sub -h $host -t $locpath -u $user -P $passwd -C 1 (without awk addition) 
2. data/backup.csv file example you receive as a result of performing the shell script?

That would greatly help me.

**Comment by RobertWojtowicz** [comment]
Without AWK:
61.95;548;kg;7;1640192484;2021-12-22 18:1:24;3.55;5

With AWK:
1640192484
