### ISSUE TITLE
Changed BT USB device and scan is empty

### ISSUE THREAD

**Issue by vobo70** [RobertWojtowicz/miscale2garmin#30]
``Hello Robert,
regarding to your advice I changed BT adapter to EDUP EP-B3536 based on RTL8761B chipset.
previously my adapter was able to scan but I had problem with range - my bathroom is next to room when I have PC with miscale2garmin software - there's one ytong wall between.
My USB port is passed through from proxmox to VM with Debian 11.
I installed firmware was you stated and even tried firmware from Debian Repo (backports non-free)
when i run scan nothing shows:
`root@miscale:/opt/miscale2garmin-5# python3 ./scanner_ble.py
Mi Body Composition Scale 2 Garmin Connect v5.3 (scanner_ble.py)

* Starting BLE scan:
* Finished BLE scan
root@miscale:/opt/miscale2garmin-5#
`
but bluetooth shows adapter:
`root@miscale:/opt/miscale2garmin-5# bluetoothctl
Agent registered
[CHG] Controller 00:E0:4C:2F:1F:2C Pairable: yes
[bluetooth]#
`
can you please help me with diagnostics?
reagrds,
Maciek

**Comment by RobertWojtowicz** [comment]
Hi, @vobo70 

What does command "hcitool dev" return ?

BR,
Robert

**Comment by vobo70** [comment]
result:
root@miscale:/opt/miscale2garmin-5# hcitool dev
Devices:
        hci0    00:E0:4C:2F:1F:2C
root@miscale:/opt/miscale2garmin-5#

**Comment by RobertWojtowicz** [comment]
Hi @vobo70 

maybe reinstall python and bluepy library? In my case it works continuously for more than a year? another thing is that I never put it in /opt/ directory, maybe some special permissions ?

BR,
Robert

**Comment by RobertWojtowicz** [comment]
Have you verified that it works from not too far away ?

**Comment by vobo70** [comment]
Hi,
Yes - the scale is less then 2m away. Usually scan finds more than 5 devices. I will try to reinstall.
Thank you.
