### ISSUE TITLE
Error uploading weight to Garmin Connect: forbidden

### ISSUE THREAD

**Issue by JoeBee01** [RobertWojtowicz/miscale2garmin#31]
There seems to be a problem in the "bodycomposition" when tries to upload to Garmin
Most likely Garmin has something changed?

**Comment by RobertWojtowicz** [comment]
Looks like it, I have the same thing.

**Comment by Martin22** [comment]
Is it possible to use another client to send data? While I hope that @abrander will fix the code, it would still be better to consider an alternative in case that doesn't happen. Unfortunately, he hasn't responded at all so far.

**Comment by RobertWojtowicz** [comment]
@Martin22 

We will have to wait, if there will be any reasonable alternative then my integration can be reworked, but I believe it will stay with bodycomposition (it works very well), the topic comes back every now and then because Garmin changes something...

BR,
Robert

**Comment by Martin22** [comment]
> @Martin22
> 
> We will have to wait, if there will be any reasonable alternative then my integration can be reworked, but I believe it will stay with bodycomposition (it works very well), the topic comes back every now and then because Garmin changes something...
> 
> BR, Robert

Wouldn't it be better to replace it the way they did it [here](https://github.com/lswiderski/WebBodyComposition/issues/1#issuecomment-1771553801)?

**Comment by app4g** [comment]
The Upload Service seems to be broken? Auth works but when trying to upload a FIT file, it returns 402 error https://github.com/petergardfjall/garminexport/issues/106

**Comment by RobertWojtowicz** [comment]
We look forward to making improvements to this module:
https://github.com/abrander/garmin-connect/issues/26

**Comment by app4g** [comment]
@RobertWojtowicz moving to the Garth method of auth if I read that correctly ?

**Comment by Martin22** [comment]
> @RobertWojtowicz moving to the Garth method of auth if I read that correctly ?

In my opinion, that transition would be the best. I just tried to create a Python client, but either I am doing something wrong or the endpoints for other things besides weight are not finished, so I can only upload weight. I am not a programmer, so I can't move forward with it anyway.

**Comment by app4g** [comment]
@Martin22 did you try the exmple.py from that project? It seems to be able to get many things.

**Comment by Martin22** [comment]
@app4g 
I was able to extract only weight from the example, and I tried to imitate the bodycomposition function. Unfortunately, it looks like it will be necessary to add additional definitions for other parameters in the Garmin class in garmiconnect. However, I am not a programmer, I can only handle the basics, and even with AI, I was not able to progress.

**Comment by RobertWojtowicz** [comment]
@Martin22 @app4g
This integration makes it possible to export the weight, I'm not a programmer either, just an administrator :)

**Comment by RobertWojtowicz** [comment]
@Martin22 @app4g @JoeBee01 

Check out new version based on YAGCC, read the README files.
https://github.com/RobertWojtowicz/miscale2garmin/releases/tag/5
