### ISSUE TITLE
Syntax error on scanner_ble.py

### ISSUE THREAD

**Issue by jendrush** [RobertWojtowicz/miscale2garmin#32]
I successfully used one of the previous versions - v4.8 of the scanner_ble_py file. Unfortunately, with the new one I am getting a syntax error

```  File "./scanner_ble.py", line 39
    Unix_time = int(dt.timestamp(dt.strptime(f"{int((data[3] << 8) | data[2])},{int(data[4])},{int(data[5])},{int(data[6])},{int(data[7])},{int(data[8])}", "%Y,%m,%d,%H,%M,%S")))
                                                                                                                                                         ^
SyntaxError: invalid syntax
```

also

During preparation 
```
sudo setcap 'cap_net_raw,cap_net_admin+eip' /usr/local/lib/python3.9/dist-packages/bluepy/bluepy-helper`
```
gives me an error

```
Failed to set capabilities on file `/usr/local/lib/python3.9/dist-packages/bluepy/bluepy-helper' (Invalid argument)
The value of the capability argument is not allowed for a file. Or the file is not a regular (non-symlink) file
```

**Comment by RobertWojtowicz** [comment]
Hi,

@jendrush 

It looks like a library error, you have not upgraded to Debian version 12 ? 
Reinstall blups - sudo pip install bluepy

**Comment by jendrush** [comment]
I will have to change the concept a bit. So far the miscale2garmin script has worked for me on a Raspberry Pi3 running Raspbian Jessie, which is an older Debian. I don't want to update it for now because I still have some sensors on the Domoticz home automation system there, I haven't transferred everything to Home Assistants yet. It is possible that I will purchase a Raspberry Pi Zero W and run the script on it. Thanks for your help. I wish there was a version where only ESP32 would suffice, without an additional MQTT server.
