### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by tinkeringtuck** [RobertWojtowicz/miscale2garmin#34]
Hello, I am hoping for some pointers on how I could further troubleshoot this issue I am experiencing: Here is the temp.log after running import_data.sh

```
jtuck@raspberrypi-scale:~/miscale2garmin-5 $ cat temp.log
Segmentation fault

Mi Body Composition Scale 2 Garmin Connect v5.9 (export_garmin.py)

* Import data: 1700448665;89.5;450
* Calculated data: 19.11.2023;21:51;89.5;25.6;25.0;63.7;3.4;51.5;3;16;31;450;<some_username>@<some_domain>.com;19.11.2023;21:51
```

I scan run the scanner_ble.py manually and it runs as expected. Running import_data.sh seems to work providing the following output, but I can't find any results in Garmin that it actually uploaded and checking the temp.log is where I found the "Segmentation Fault" 

```
jtuck@raspberrypi-scale:~/miscale2garmin-5 $ ./import_data.sh
Mi Body Composition Scale 2 Garmin Connect v5.9 (import_data.sh)

* backup.csv file exists, check if temp.log exists
* temp.log file exists, checking for new data
* Importing data from a BLE scanner
* Saving import 1700448665 to backup.csv file
* Calculating data from import 1700448665, upload to Garmin Connect
* Data upload to Garmin Connect is complete
* Saving calculated data from import 1700448665 to backup.csv file
```

Any ideas for how I can get to the bottom of my issue?

**Comment by RobertWojtowicz** [comment]
> Hello, I am hoping for some pointers on how I could further troubleshoot this issue I am experiencing: Here is the temp.log after running import_data.sh
> 
> ```
> jtuck@raspberrypi-scale:~/miscale2garmin-5 $ cat temp.log
> Segmentation fault
> 
> Mi Body Composition Scale 2 Garmin Connect v5.9 (export_garmin.py)
> 
> * Import data: 1700448665;89.5;450
> * Calculated data: 19.11.2023;21:51;89.5;25.6;25.0;63.7;3.4;51.5;3;16;31;450;<some_username>@<some_domain>.com;19.11.2023;21:51
> ```
> 
> I scan run the scanner_ble.py manually and it runs as expected. Running import_data.sh seems to work providing the following output, but I can't find any results in Garmin that it actually uploaded and checking the temp.log is where I found the "Segmentation Fault" 
> 
> ```
> jtuck@raspberrypi-scale:~/miscale2garmin-5 $ ./import_data.sh
> Mi Body Composition Scale 2 Garmin Connect v5.9 (import_data.sh)
> 
> * backup.csv file exists, check if temp.log exists
> * temp.log file exists, checking for new data
> * Importing data from a BLE scanner
> * Saving import 1700448665 to backup.csv file
> * Calculating data from import 1700448665, upload to Garmin Connect
> * Data upload to Garmin Connect is complete
> * Saving calculated data from import 1700448665 to backup.csv file
> ```
> 
> 
> Any ideas for how I can get to the bottom of my issue?

Are you using the correct version of YAGCC for the raspberry pi ?, I will also add this as an error in the log.

**Comment by tinkeringtuck** [comment]
Yes, I believe I followed these instructions here for [ARM Raspberry Pi Zero W](https://github.com/RobertWojtowicz/miscale2garmin/blob/master/manuals/ARM_ble.md)

Is there anyway for me to verify or run YAGCC manually to test/isolate it?

**Comment by RobertWojtowicz** [comment]
Which version of the architecture you are using and are you sure the right package:
Raspberry Pi OS | Debian 11 (32-bit) use linux-arm.zip
Raspberry Pi OS | Debian 11 (64-bit) use linux-arm64.zip

Try running the YAGCC program manually:
https://github-production-user-asset-6210df.s3.amazonaws.com/2623594/278115701-202f0ad3-9d9e-4026-a547-84a014663777.png

**Comment by tinkeringtuck** [comment]
yes, I am running Debian 11 (32-bit) on Pi 0 W. Would you recommend 64-bit or another architecture that others have had more success with? 

I reinstalled re followed the instructions and installed the latest linux-arm.zip just to be sure, with version 6, since it came out a few days ago. 

Still getting Segmentation Fault when running YAGCC. Maybe I should try re-flashing my Pi with fresh OS? 

```
$ ./YAGCC
Segmentation fault
```

**Comment by RobertWojtowicz** [comment]
Hi,

I will try to check at the weekend if problem occurs on rpi 0 W, I use a virtual machine, but I have rpi 0 W for testing. If bug occurs I will report it to author of the program.

BR,
Robert

**Comment by massovercharge** [comment]
I am observing the same error message, I'm running Raspberry Pi OS | Debian 11 (32-bit) with linux-arm.tar.gz on a Raspberry Pi Zero W v1.1, freshly installed and updated today. However, my scale is a Mi Body Composition Scale (1) not 2. Would this make any difference?


```
 cat /home/pi/miscale2garmin-6/temp.log
Segmentation fault

Mi Body Composition Scale 2 Garmin Connect v5.9 (export_garmin.py)

* Import data: 1700768160;69.2;467
* Calculated data: 23.11.2023;20:36;69.2;22.3;18.1;53.8;2.9;56.2;5;9;24;467;user@domain;23.11.2023;20:43
```

```
nano export_garmin.py
 /home/pi/miscale2garmin-6/import_data.sh
Mi Body Composition Scale 2 Garmin Connect v6.0 (import_data.sh)

23.11.2023-20:43:04 * Creating backup.csv file, check if temp.log exists
23.11.2023-20:43:04 * Creating temp.log file, checking for new data
23.11.2023-20:43:04 * Importing data from a BLE scanner
23.11.2023-20:43:06 * Saving import 1700768160 to backup.csv file
23.11.2023-20:43:07 * Calculating data from import 1700768160, upload to Garmin Connect
23.11.2023-20:43:07 * Data upload to Garmin Connect is complete
23.11.2023-20:43:07 * Saving calculated data from import 1700768160 to backup.csv file
```

**Comment by RobertWojtowicz** [comment]
I transferred the solution to YAGCC from bodycomposition and this is a new type of error, I will add to the script, while I will report the error to the author of YAGCC.
Problem is related to package for arm

BR,
Robert

**Comment by lswiderski** [comment]
@RobertWojtowicz 
@tinkeringtuck 
@massovercharge 
Hi Guys,

Unfortunately I can't do much here, since dotnet do not support ARMv6, (only ARMv7 +) and Pi Zero have that kind of chip. 
https://github.com/lswiderski/yet-another-garmin-connect-client/issues/5#issuecomment-1827502765

But I have possible solution. For my other projects (Android App and Web app) I'm hosting YAGCC as WEB API
https://frog01-20364.wykr.es/ 
So you can pass received data to /upload endpoint by POST. Or you can host your own instance of the API in docker somewhere else

**Comment by tinkeringtuck** [comment]
closed by #35

**Comment by RobertWojtowicz** [comment]
@tinkeringtuck @massovercharge check out new version :)
https://github.com/RobertWojtowicz/miscale2garmin

**Comment by tinkeringtuck** [comment]
> @tinkeringtuck @massovercharge @lswiderski check out new version :) https://github.com/RobertWojtowicz/miscale2garmin
> 
> PS. Nice project: https://github.com/cyberjunky/python-garminconnect
> 
> BR, Robert

a little but delayed, but I was able to get my pi 0 W up and running with the project, which frees up my pi3b+ for other projects :) Thanks!
