### ISSUE TITLE
Support for pounds? 

### ISSUE THREAD

**Issue by mikelikesspam** [RobertWojtowicz/miscale2garmin#36]
Hi Robert, since weightlogger no longer works with Garmin after 2fA, I am using miscale2garmin and it works great.  Thank you.  Entering weight in kgs adds another step (conversion in a calculator) which though trivial, is needed each and every time.

Are reason you would not consider adding weight entry in pounds?

thanks, mike

**Comment by RobertWojtowicz** [comment]
Hi,

Functionality requires too much change, which also includes external modules, I will not help with this, sorry.

BR,
Robert

**Comment by RobertWojtowicz** [comment]
@mikelikesspam

**Comment by mikelikesspam** [comment]
Thanks for considering and responding.  I use manual entry, so I assume this does not apply.  But thank you for suggesting the alternative.
