### ISSUE TITLE
New faster way

### ISSUE THREAD

**Issue by pervolianinen** [RobertWojtowicz/miscale2garmin#6]
There is more faster and powerfull metode.
No nead masquitto and mqtt broker.
Use ESPhome rot esp32 with native component xiaomi_miscale.
The other way same as in your topic.
Thanks for your work!

**Comment by RobertWojtowicz** [comment]
Hi @pervolianinen

Can you provide a specific link to this solution ?

Best Regards,
Robert

**Comment by pervolianinen** [comment]
> Hi @pervolianinen
> 
> Can you provide a specific link to this solution ? https://github.com/dckiller51/bodymiscale ?
> 
> It seems to me that this is not an easier solution.
> 
> Best Regards, Robert

Esphome component. 
https://esphome.io/components/sensor/xiaomi_miscale.html

**Comment by RobertWojtowicz** [comment]
> > Hi @pervolianinen
> > Can you provide a specific link to this solution ? https://github.com/dckiller51/bodymiscale ?
> > It seems to me that this is not an easier solution.
> > Best Regards, Robert
> 
> Esphome component. https://esphome.io/components/sensor/xiaomi_miscale.html I test it. work grate. Home assistent can sent to garmin, with utility with command_line command. Data can be collect and visualise using grafana and influxdb

It's easier for you if you have everything configured, rather than starting from scratch :)

**Comment by pervolianinen** [comment]
> > > Hi @pervolianinen
> > > Can you provide a specific link to this solution ? https://github.com/dckiller51/bodymiscale ?
> > > It seems to me that this is not an easier solution.
> > > Best Regards, Robert
> > 
> > 
> > Esphome component. https://esphome.io/components/sensor/xiaomi_miscale.html I test it. work grate. Home assistent can sent to garmin, with utility with command_line command. Data can be collect and visualise using grafana and influxdb
> 
> It's easier for you as you have everything configured rather than starting from scratch :)
1. This is more stable version (project for esp32 was many time tested in Russia). Esphome easy to bild. Nead to copy 10 lines from documentation.
2. Home assistent 1 system masquitto + mqtt brocker 2 systems. Its easy to start and use and more power, has many instructions.
3. HA has component to parse implementation data from mi scale.

**Comment by RobertWojtowicz** [comment]
> > It's easier for you as you have everything configured rather than starting from scratch :)
> 
>     1. This is more stable version (project for esp32 was many time tested in Russia). Esphome easy to bild. Nead to copy 10 lines from documentation.
> 
>     2. Home assistent 1 system masquitto + mqtt brocker 2 systems. Its easy to start and use and more power, has many instructions.
> 
>     3. HA has component to parse implementation data from mi scale.

I've been using my solution for 2 years and I also don't see any problems, as I wrote if you only need Garmin integration the simplest solution seems to be the described project. I don't look at other HA system possibilities :)

**Comment by RobertWojtowicz** [comment]
I added a new version 3.0 supporting direct synchronization, more easy :)
