### ISSUE TITLE
bodycomposition: Exec format error

### ISSUE THREAD

**Issue by pascaltsc** [RobertWojtowicz/miscale2garmin#8]
Hi Robert,
thank you for your great project.
it was exactly what i was looking for.

There is only one problem when trying to process the data before it is uploaded.

>sudo ./import_ble.sh 
>Mi Body Composition Scale 2 Garmin Connect v3.0 (import_ble.sh)

>Data backup file exists, checking for new data
>Importing and calculating data to upload
>Data upload to Garmin Connect is complete

(I have to start it via sudo otherwise there are problems to execute/start btle.py)

but when checking the log:

`
cat temp.log 
sh: 1: /home/pi/miscale2garmin-3.0/bodycomposition: Exec format error
Mi Body Composition Scale 2 Garmin Connect v3.0 (export_garmin.py)
Processed file: 1644148841.tlog
`

If you need more information let me know.

Thanks for your effort and your time.
Cheers
Pascal

**Comment by RobertWojtowicz** [comment]
Hi, @pascaltsc 

Have you downloaded the version for arm? 👍 
https://github.com/davidkroell/bodycomposition/releases/download/v1.6.2/bodycomposition_1.6.2_Linux_arm64.tar.gz

What is the result of executing scanner.py ?

BR,
Robert

**Comment by pascaltsc** [comment]
Hi Robert
your hunch was correct, it seems as if I didn't pay attention to the Raspi. 
After downloading the ARM Version it worked like a charm.

The scanner.py part was clean.

Sorry for bothering you .
Have a nice Sunday evening & Cheers
