### ISSUE TITLE
Issue with upload to garmin

### ISSUE THREAD

**Issue by lsassx64** [RobertWojtowicz/miscale2garmin#9]
As the tittle sugeest....i get the error 
sh: 1: /home/pi/miscale2garmin-3.0/bodycomposition: Exec format error

Any suggestions on what could be the issue?

**Comment by RobertWojtowicz** [comment]
This is the same case: https://github.com/RobertWojtowicz/miscale2garmin/issues/8

According to README:
Download and extract to your home directory (e.g. "/home/robert/"), make a files executable (note: choose correct version of boodycomposition depending on your computer, e.g. "_Linux_x86_64.tar.gz")

Have you downloaded version for arm? :
https://github.com/davidkroell/bodycomposition/releases/download/v1.6.2/bodycomposition_1.6.2_Linux_arm64.tar.gz

BR,
Robert
